### ISSUE TITLE
Update README with current contact details

### ISSUE THREAD

**Issue by lxutopia** [Sydarkivera/RecursiveTar#6]
Should probably update the README with contact details of current maintainers, or remove contact details alltogether.

**Comment by karinbredenberg** [comment]
Change so asked to add an issue instead.

**Comment by karinbredenberg** [comment]
Are there additions needed to the text like any/some requirements to be able to run the code? 

Does it become like a exe file or is something elses needed to be able to run it?

**Comment by lxutopia** [comment]
GNU Make and GCC is needed to compile from source. We should probably give some instructions how to compile for different platforms.
